(function(g){var window=this;var lqa=function(a,b){return g.Ub(a,b)},g6=function(){},mqa=function(a){if(a.Bc&&"function"==typeof a.Bc)return a.Bc();
if(g.Da(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},nqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.Da(a))(0,g.y)(a,b,void 0);else{if(a.Pd&&"function"==typeof a.Pd)var c=a.Pd();else if(a.Bc&&"function"==typeof a.Bc)c=void 0;else if(g.La(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=mqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},h6=function(a){g.tn(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},i6=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.yn(a.l,b,c)},j6=function(a){return(a=g.Ro(a))?new ActiveXObject(a):new XMLHttpRequest},k6=function(a,b){return b+" ["+a.Y+" "+a.D+" "+a.getStatus()+"]"},oqa=function(a){return"content-type"==a.toLowerCase()},l6=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.u.clearTimeout(a.F),a.F=null)},pqa=function(a){return g.Ld&&g.ld(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},m6=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},n6=function(a,b){if(a.g){l6(a);
var c=a.g,d=a.R[0]?g.Ha:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},o6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;m6(a);n6(a)},p6=function(a){return a.g?a.g.readyState:0},q6=function(a){if(a.i&&"undefined"!=typeof g.cZ)if(a.R[1]&&4==p6(a)&&2==a.getStatus())k6(a,"Local request error detected and ignored");
else if(a.B&&4==p6(a))g.Fg(a.zw,0,a);else if(a.dispatchEvent("readystatechange"),4==p6(a)){k6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Rg(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!qqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<p6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";m6(a)}}finally{n6(a)}}},r6=function(a){g.Pf.call(this);
this.headers=new g.hn;this.M=a||null;this.i=!1;this.R=this.g=null;this.Y=this.D="";this.u=0;this.l="";this.o=this.aa=this.B=this.P=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},s6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},rqa=function(a,b){var c=[];
g.Qk(b,function(d){try{var e=g.hp.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.gp(e)&&c.push(d):c.push(d)},a);
return c},sqa=function(a,b){var c=rqa(a,b);
(0,g.y)(c,function(d){g.hp.prototype.remove.call(this,d)},a)},t6=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},tqa=function(a,b){g.$a(a,b)||a.push(b)},u6=function(a){var b=0,c;
for(c in a)b++;return b},v6=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},uqa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},vqa=function(a,b,c,d){var e=new g.ln(null,void 0);
a&&g.mn(e,a);b&&g.nn(e,b);c&&g.on(e,c);d&&(e.i=d);return e},w6=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return uqa(a)},x6=function(){this.g=[];
this.i=[]},y6=function(a,b){g.mq[a]=!0;
var c=g.kq();c&&c.publish.apply(c,arguments);g.mq[a]=!1},z6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.hn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",wqa(this,a.capabilities||""),xqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},wqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(lqa,yqa)).forEach(function(c){a.capabilities.add(c)})},xqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},A6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},B6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},C6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},zqa=function(a){return new A6(a)},D6=function(a){return g.Ka(a)?(0,g.ge)(a,zqa):[]},E6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},F6=function(a){return g.Ka(a)?"["+(0,g.ge)(a,E6).join(",")+"]":"null"},G6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Aqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},H6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},I6=function(a,b){return g.Xa(a,function(c){return B6(c,b)})},J6=function(a){try{var b=(0,g.Jt)(),c=(0,g.It)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Bqa=function(){var a=(0,g.It)();
a&&sqa(a,a.g.qf(!0))},K6=function(){var a=g.Lt("yt-remote-connected-devices")||[];
g.qb(a);return a},Cqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},L6=function(a){g.Kt("yt-remote-connected-devices",a,86400)},N6=function(){if(M6)return M6;
var a=g.Lt("yt-remote-device-id");a||(a=G6(),g.Kt("yt-remote-device-id",a,31536E3));for(var b=K6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return M6=d},O6=function(){var a=K6(),b=N6();
g.$a(a,b);g.Mt()&&g.sb(a,b);a=Cqa(a);if(0==a.length)try{g.Ks("remote_sid")}catch(c){}else try{g.Js("remote_sid",a.join(","),-1)}catch(c){}},P6=function(){return g.Lt("yt-remote-session-browser-channel")},Q6=function(){return g.Lt("yt-remote-local-screens")||[]},R6=function(){g.Kt("yt-remote-lounge-token-expiration",!0,86400)},Dqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(Q6(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.lj)(c,function(d){return!g.$a(b,d)})&&R6();
g.Kt("yt-remote-local-screens",a,31536E3)},Eqa=function(a,b){g.Kt("yt-remote-session-browser-channel",a);
g.Kt("yt-remote-session-screen-id",b);var c=K6(),d=N6();g.$a(c,d)||c.push(d);L6(c);O6()},S6=function(a){a||(J6("yt-remote-session-screen-id"),J6("yt-remote-session-video-id"));
O6();a=K6();g.cb(a,N6());L6(a)},U6=function(){if(!T6){var a=g.rp();
a&&(T6=new g.bp(a))}return T6?!!T6.get("yt-remote-use-staging-server"):!1},V6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},W6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Y6=function(a){a.length?X6(a.shift(),function(){Y6(a)}):Z6()},Fqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},X6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Z6=function(){var a=W6();
a&&a(!1,"No cast extension found")},$6=function(){if(Gqa){var a=2,b=W6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;X6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Z6,c)}},Hqa=function(){$6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Y6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},a7=function(a,b,c){g.A.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Yc=b;this.u=(0,g.x)(this.JD,this);this.g=!1;this.i=0;this.l=this.Aa=null;this.o=[]},b7=function(){},c7=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ca=new g.zn(this);this.i=new g.Eg;this.i.setInterval(250)},e7=function(a,b,c){a.di=1;
a.Zf=h6(b.clone());a.wh=c;a.u=!0;d7(a,null)},f7=function(a,b,c,d,e){a.di=1;
a.Zf=h6(b.clone());a.wh=null;a.u=c;e&&(a.sA=!1);d7(a,d)},d7=function(a,b){a.Ki=(0,g.D)();
g7(a);a.Eg=a.Zf.clone();i6(a.Eg,"t",a.A);a.nl=0;a.tc=a.g.Pp(a.g.Vk()?b:null);0<a.xq&&(a.ho=new g.Il((0,g.x)(a.zB,a,a.tc),a.xq));a.ca.da(a.tc,"readystatechange",a.GM);var c=a.bh?g.bc(a.bh):{};a.wh?(a.No="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Eg,a.No,a.wh,c)):(a.No="GET",a.sA&&!g.Nd&&(c.Connection="close"),a.tc.send(a.Eg,a.No,null,c));a.g.Be(1)},n7=function(a,b,c){for(var d=!0;!a.Pg&&a.nl<c.length;){var e=Iqa(a,c);
if(e==h7){4==b&&(a.qg=4,i7(15),d=!1);break}else if(e==j7){a.qg=4;i7(16);d=!1;break}else k7(a,e)}4==b&&0==c.length&&(a.qg=1,i7(17),d=!1);a.Ee=a.Ee&&d;d||(l7(a),m7(a))},Iqa=function(a,b){var c=a.nl,d=b.indexOf("\n",c);
if(-1==d)return h7;c=Number(b.substring(c,d));if(isNaN(c))return j7;d+=1;if(d+c>b.length)return h7;var e=b.substr(d,c);a.nl=d+c;return e},q7=function(a,b){a.Ki=(0,g.D)();
g7(a);var c=b?window.location.hostname:"";a.Eg=a.Zf.clone();g.tn(a.Eg,"DOMAIN",c);g.tn(a.Eg,"t",a.A);try{a.Ie=new ActiveXObject("htmlfile")}catch(n){l7(a);a.qg=7;i7(22);m7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in o7)k=o7[l];else if(l in p7)k=o7[l]=p7[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
o7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.Ie.open();a.Ie.write(g.Mc(c));a.Ie.close();a.Ie.parentWindow.m=(0,g.x)(a.TL,a);a.Ie.parentWindow.d=(0,g.x)(a.Az,a,!0);a.Ie.parentWindow.rpcClose=(0,g.x)(a.Az,a,!1);c=a.Ie.createElement("DIV");a.Ie.parentWindow.document.body.appendChild(c);d=g.Cc(a.Eg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.Be(1)},g7=function(a){a.Ct=(0,g.D)()+a.o;
Jqa(a,a.o)},Jqa=function(a,b){if(null!=a.aj)throw Error("WatchDog timer not null");
a.aj=r7((0,g.x)(a.dM,a),b)},s7=function(a){a.aj&&(g.u.clearTimeout(a.aj),a.aj=null)},m7=function(a){a.g.xw()||a.Pg||a.g.Tn(a)},l7=function(a){s7(a);
g.pf(a.ho);a.ho=null;a.i.stop();g.Bn(a.ca);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Ie&&(a.Ie=null)},k7=function(a,b){try{a.g.uz(a,b),a.g.Be(4)}catch(c){}},Lqa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Kqa(a,b,function(k){k?c(!0):g.u.setTimeout(function(){Lqa(a,b,c,d,f)},f)})}},Kqa=function(a,b,c){var d=new Image;
d.onload=function(){try{t7(d),c(!0)}catch(e){}};
d.onerror=function(){try{t7(d),c(!1)}catch(e){}};
d.onabort=function(){try{t7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{t7(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
v6(d,a)},t7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Mqa=function(a){this.g=a;
this.i=new b7},Nqa=function(a){var b=u7(a.g,a.mj,"/mail/images/cleardot.gif");
h6(b);Lqa(b.toString(),5E3,(0,g.x)(a.PC,a),3,2E3);a.Be(1)},w7=function(a){var b=a.g.F;
if(null!=b)i7(5),b?(i7(11),v7(a.g,a,!1)):(i7(12),v7(a.g,a,!0));else if(a.Hd=new c7(a,void 0,void 0,void 0),a.Hd.bh=a.uq,b=a.g,b=u7(b,b.Vk()?a.Sj:null,a.wq),i7(5),!g.Ld||g.md(10))i6(b,"TYPE","xmlhttp"),f7(a.Hd,b,!1,a.Sj,!1);else{i6(b,"TYPE","html");var c=a.Hd;a=!!a.Sj;c.di=3;c.Zf=h6(b.clone());q7(c,a)}},x7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new b7;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Oqa=function(a,b){this.g=a;
this.map=b;this.context=null},Pqa=function(a){g.rf.call(this,"statevent",a)},Qqa=function(a,b){g.rf.call(this,"timingevent",a);
this.size=b},Rqa=function(a){g.rf.call(this,"serverreachability",a)},Uqa=function(a){Sqa(a);
if(3==a.g){var b=a.zk++,c=a.qm.clone();g.tn(c,"SID",a.l);g.tn(c,"RID",b);g.tn(c,"TYPE","terminate");y7(a,c);b=new c7(a,a.l,b,void 0);b.di=2;b.Zf=h6(c.clone());v6(new Image,b.Zf.toString());b.Ki=(0,g.D)();g7(b)}Tqa(a)},Vqa=function(a){a.hD(1,0);
a.qm=u7(a,null,a.tq);z7(a)},Sqa=function(a){a.gg&&(a.gg.abort(),a.gg=null);
a.Tb&&(a.Tb.cancel(),a.Tb=null);a.rf&&(g.u.clearTimeout(a.rf),a.rf=null);A7(a);a.Ed&&(a.Ed.cancel(),a.Ed=null);a.ng&&(g.u.clearTimeout(a.ng),a.ng=null)},Wqa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Oqa(a.hI++,b));2!=a.g&&3!=a.g||z7(a)},z7=function(a){a.Ed||a.ng||(a.ng=r7((0,g.x)(a.zz,a),0),a.Wh=0)},Yqa=function(a,b){if(1==a.g){if(!b){a.zk=Math.floor(1E5*Math.random());
var c=a.zk++,d=new c7(a,"",c,void 0);d.bh=null;var e=B7(a),f=a.qm.clone();g.tn(f,"RID",c);g.tn(f,"CVER","1");y7(a,f);e7(d,f,e);a.Ed=d;a.g=2}}else 3==a.g&&(b?Xqa(a,b):0==a.i.length||a.Ed||Xqa(a))},Xqa=function(a,b){if(b)if(6<a.Qg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.zk-1;var d=B7(a)}else c=b.B,d=b.wh;else c=a.zk++,d=B7(a);var e=a.qm.clone();g.tn(e,"SID",a.l);g.tn(e,"RID",c);g.tn(e,"AID",a.oi);y7(a,e);c=new c7(a,a.l,c,a.Wh+1);c.bh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ed=c;e7(c,e,d)},y7=function(a,b){if(a.Vc){var c=a.Vc.Vv();
c&&g.Kb(c,function(d,e){g.tn(b,e,d)})}},B7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Qg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Qg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Zqa=function(a){a.Tb||a.rf||(a.B=1,a.rf=r7((0,g.x)(a.yz,a),0),a.Oh=0)},C7=function(a){if(a.Tb||a.rf||3<=a.Oh)return!1;
a.B++;a.rf=r7((0,g.x)(a.yz,a),$qa(a,a.Oh));a.Oh++;return!0},v7=function(a,b,c){a.Lo=c;
a.Ne=b.Bf;a.A||Vqa(a)},A7=function(a){null!=a.Ug&&(g.u.clearTimeout(a.Ug),a.Ug=null)},$qa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},D7=function(a,b){if(2==b||9==b){var c=null;
a.Vc&&(c=null);var d=(0,g.x)(a.mN,a);c||(c=new g.ln("//www.google.com/images/cleardot.gif"),h6(c));Kqa(c.toString(),1E4,d)}else i7(2);ara(a,b)},ara=function(a,b){a.g=0;
a.Vc&&a.Vc.Wu(b);Tqa(a);Sqa(a)},Tqa=function(a){a.g=0;
a.Ne=-1;if(a.Vc)if(0==a.o.length&&0==a.i.length)a.Vc.Bp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Vc.Bp(b)}},u7=function(a,b,c){var d=g.un(c);
if(""!=d.g)b&&g.nn(d,b+"."+d.g),g.on(d,d.u);else{var e=window.location;d=vqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Aj&&g.Kb(a.Aj,function(f,k){g.tn(d,k,f)});
g.tn(d,"VER",a.Qg);y7(a,d);return d},r7=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},i7=function(a){E7.dispatchEvent(new Pqa(E7,a))},bra=function(){},cra=function(a,b){this.action=a;
this.params=b||{}},F7=function(a,b){g.A.call(this);
this.g=new g.J(this.LL,0,this);g.B(this,this.g);this.Yc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},G7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.ap;this.i=new F7(this.RM,this);this.g=null;this.jb=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},dra=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Lo,sessionId:a.g.l,arrayId:a.g.oi}},era=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&Yqa(a.g),Uqa(a.g));a.D=0},H7=function(a){return!!a.g&&3==a.g.g},fra=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},I7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Rg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Sg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},J7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ah(c+b,{})},K7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),oe:g.Qa(a.u,e)};c&&(a.wb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.er(b,a)},jra=function(){var a=gra;
hra();L7.push(a);ira(L7)},M7=function(a,b){hra();
var c=L7,d=kra(a,String(b));0==c.length?lra(d):(ira(c),(0,g.y)(c,function(e){e(d)}))},hra=function(){L7||(L7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",L7,void 0))},lra=function(a){var b=(N7+1)%50;
N7=b;O7[b]=a;P7||(P7=49==b)},ira=function(a){var b=O7;
if(b[0]){var c=N7,d=P7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
O7=Array(50);N7=-1;P7=!1}},kra=function(a,b){var c=((0,g.D)()-mra)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},Q7=function(a){g.N.call(this);
this.B=a;this.g=[]},nra=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},ora=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!H6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=nra(a,b[d])||c;return c},pra=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},R7=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Aa=NaN},T7=function(a){Q7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;S7(this);this.info("Initializing with "+F6(this.g))},qra=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=J7(a.l,"/pairing/get_lounge_token_batch");
K7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.TD,a),(0,g.x)(a.SD,a))}},S7=function(a){var b=D6(Q6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return ora(a,b)},U7=function(a,b){Dqa((0,g.ge)(a.g,C6));
b&&R6()},W7=function(a,b){g.N.call(this);
this.A=b;var c=g.Lt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;V7("Initialized with "+g.Jg(this.g))},rra=function(a,b,c){var d=J7(a.u,"/pairing/get_screen_availability");
K7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},X7=function(a,b){a:if(u6(b)!=u6(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(V7("Updated online screens: "+g.Jg(a.g)),a.g=b,a.N("screenChange"));sra(a)},Y7=function(a){isNaN(a.l)||g.jq(a.l);
a.l=g.hq((0,g.x)(a.Gs,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},V7=function(a){M7("OnlineScreenService",a)},tra=function(a){var b={};
(0,g.y)(a.A(),function(c){c.token?b[c.token]=c.id:this.Ib("Requesting availability of screen w/o lounge token.")});
return b},sra=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Kt("yt-remote-online-screen-ids",a.join(","),60):J6("yt-remote-online-screen-ids")},Z7=function(a){Q7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};ura(this)},wra=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Rd();if(k=(c?I6(k,c):null)||I6(k,b)){k.uuid=b;var l=$7(a,k);rra(a.i,l,function(m){e(m?l:null)})}else c?vra(a,c,(0,g.x)(function(m){var n=$7(this,new A6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));rra(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},xra=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},vra=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={wb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.er(J7(a.A,"/pairing/get_lounge_token_batch"),e)},yra=function(a){a.g=a.l.Rd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+F6(a.g))},ura=function(a){a8(a);
a.l=new T7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.bE,a));yra(a);a.o=D6(g.Lt("yt-remote-automatic-screen-cache")||[]);a8(a);a.info("Initializing automatic screens: "+F6(a.o));a.i=new W7(a.A,(0,g.x)(a.Rd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},$7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=I6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Kt("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,C6)));a8(a);a.u[b.uuid]=b.id;g.Kt("yt-remote-device-id-map",a.u,31536E3);return b},a8=function(a){a.u=g.Lt("yt-remote-device-id-map")||{}},b8=function(a,b,c){g.N.call(this);
this.R=c;this.F=a;this.i=b;this.l=null},c8=function(a,b){M7(a.R,b)},d8=function(a,b){b8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.SN,this);this.u=(0,g.x)(this.oM,this);this.o=g.hq((0,g.x)(function(){zra(this,null)},this),12E4)},Ara=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Jg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){c8(this,"Failed to send message: getMdxSessionStatus.")},a)):c8(a,"Sending yt message without session: "+g.Jg(b))},zra=function(a,b){g.jq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.Vn,a),d=(0,g.x)(a.Ud,a);a.nw(b,c,d,5)}}else a.Ud(Error("Waiting for session status timed out."))},e8=function(a,b,c){b8.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ha;this.A=NaN;this.I=(0,g.x)(this.VN,this);this.g=g.Ha},Bra=function(a){a.g=a.F.EB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.Vn(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Ud(b)},a))},Cra=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}U6()&&(b.env_useStageMdx=1);return g.Zg(b)},f8=function(a,b){b8.call(this,a,b,"ManualSession");
this.g=g.hq((0,g.x)(this.ri,this,null),150)},g8=function(a,b,c,d){g.N.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.TK,this)},Dra=function(a,b){return b?g.Xa(a.l,function(c){return B6(b,c.label)},a):null},h8=function(a){M7("Controller",a)},gra=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},i8=function(a){return a.u||!!a.l.length||!!a.g},j8=function(a,b,c){b!=a.g&&(g.pf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.xz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ri(null)):a.N("yt-remote-cast2-session-change",null))},Era=function(a){var b=a.i.DB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&B6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Dra(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Kra=function(a,b,c,d,e,f,k){Fra()?Gra(b,e,f,k)&&(l8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Hra(a,c):(window.__onGCastApiAvailable=function(l,m){l?Hra(a,c):(m8("Failed to load cast API: "+m),n8(!1),l8(!1),J6("yt-remote-cast-available"),J6("yt-remote-cast-receiver"),Ira(),c(!1))},d?g.uq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Hqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Z6():($6(),Y6(Jra.map(Fqa))))):k8("Cannot initialize because not running Chrome")},Ira=function(){k8("dispose");
var a=o8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Lra(!1);g.pq(p8);p8.length=0},q8=function(){return!!g.Lt("yt-remote-cast-installed")},Mra=function(){var a=g.Lt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Nra=function(){k8("clearCurrentReceiver");
J6("yt-remote-cast-receiver")},Ora=function(){return q8()?o8()?o8().getCastSession():(m8("getCastSelector: Cast is not initialized."),null):(m8("getCastSelector: Cast API is not installed!"),null)},s8=function(){q8()?o8()?r8()?(k8("Requesting cast selector."),o8().requestSession()):(k8("Wait for cast API to be ready to request the session."),p8.push(g.oq("yt-remote-cast2-api-ready",s8))):m8("requestCastSelector: Cast is not initialized."):m8("requestCastSelector: Cast API is not installed!")},t8=
function(a,b){r8()?o8().setConnectedScreenStatus(a,b):m8("setConnectedScreenStatus called before ready.")},Fra=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.tx||a},Pra=function(a,b){o8().init(a,b)},Gra=function(a,b,c,d){var e=!1;
o8()||(a=new g8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Kt("yt-remote-cast-available",f);y6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){k8("onReceiverSelected: "+f.friendlyName);
g.Kt("yt-remote-cast-receiver",f);y6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){k8("onReceiverResumed: "+f.friendlyName);
g.Kt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){k8("onSessionChange: "+E6(f));
f||J6("yt-remote-cast-receiver");y6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
k8("cloudview.createSingleton_: "+e);return e},o8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Hra=function(a,b){n8(!0);
l8(!1);Pra(a,function(c){c?(Lra(!0),g.rq("yt-remote-cast2-api-ready")):(m8("Failed to initialize cast API."),n8(!1),J6("yt-remote-cast-available"),J6("yt-remote-cast-receiver"),Ira());b(c)})},k8=function(a){M7("cloudview",a)},m8=function(a){M7("cloudview",a)},n8=function(a){k8("setCastInstalled_ "+a);
g.Kt("yt-remote-cast-installed",a)},r8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Lra=function(a){k8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},l8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},u8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Oe=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},v8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Oe=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},w8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},x8=function(a,b){a.B=b;
a.A=(0,g.D)()},y8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},z8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&v8(a)},A8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Oe;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},C8=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new x6;this.l=this.i=null;this.F=(0,g.x)(this.RI,this);this.B=(0,g.x)(this.Ck,this);this.D=(0,g.x)(this.QI,this);this.H=(0,g.x)(this.eJ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ft,this),Qra(this))):c=3;0!=c&&(b?this.Ft(c):g.hq((0,g.x)(function(){this.Ft(c)},this),0));
var d=Ora();d&&B8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},D8=function(a){return new u8(a.o.getPlayerContextData())},Qra=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.QK,b),this))},a)},Rra=function(a){(0,g.y)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},E8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},G8=function(a,b,c){var d=D8(a);
x8(d,c);-1E3!=d.playerState&&(d.playerState=b);F8(a,d)},H8=function(a,b,c){a.o.sendMessage(b,c)},F8=function(a,b){Rra(a);
a.o.setPlayerContextData(A8(b));Qra(a)},B8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.Ck(null));
a.l=b;a.l&&(M7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.Ck(a.l.media[0]))},Sra=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=D8(a);b.contentId!=d.videoId&&M7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;x8(d,a.i.getEstimatedTime());F8(a,d)}else M7("CP","No cast media video. Ignoring state update.")},I8=function(a,b,c){return(0,g.x)(function(d){this.Ib("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ib("Retrying "+b+" using MDx browser channel."),H8(this,b,c))},a)},J8=function(a,b,c){g.N.call(this);
this.u=NaN;this.I=!1;this.D=this.B=this.F=this.H=NaN;this.R=[];this.o=this.A=this.l=this.Pa=this.g=null;this.P=a;this.R.push(g.ns(window,"beforeunload",(0,g.x)(this.MD,this)));this.i=[];this.Pa=new u8;this.M=b.id;this.g=Tra(this,c);this.g.subscribe("handlerOpened",this.VI,this);this.g.subscribe("handlerClosed",this.SI,this);this.g.subscribe("handlerError",this.TI,this);this.g.subscribe("handlerMessage",this.UI,this);fra(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.Mt()&&g.Kt("yt-remote-session-video-id",d)},this)},K8=function(a){M7("conn",a)},Tra=function(a,b){return new G7(J7(a.P,"/bc"),b)},L8=function(a,b){a.N("proxyStateChange",b)},Ura=function(a){a.u=g.hq((0,g.x)(function(){K8("Connecting timeout");
this.Sh(1)},a),2E4)},M8=function(a){g.jq(a.u);
a.u=NaN},N8=function(a){g.jq(a.H);
a.H=NaN},Vra=function(a){O8(a);
a.F=g.hq((0,g.x)(function(){P8(this,"getNowPlaying")},a),2E4)},O8=function(a){g.jq(a.F);
a.F=NaN},Xra=function(a,b){b&&(M8(a),N8(a));
b==(H7(a.g)&&isNaN(a.u))?b&&(L8(a,1),P8(a,"getSubtitlesTrack")):b?(a.lw()&&a.Pa.reset(),L8(a,1),P8(a,"getNowPlaying"),Wra(a)):a.Sh(1)},Yra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Xb(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.N("remotePlayerChange"))},Zra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;z8(a.Pa,c,d);a.N("remoteQueueChange")},asa=function(a,b){b.params=b.params||{};
Zra(a,b);$ra(a,b);a.N("autoplayDismissed")},$ra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
x8(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?Vra(a):O8(a);a.N("remotePlayerChange")},bsa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);x8(a.Pa,isNaN(c)?0:c);a.N("remotePlayerChange")}},csa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.N("remotePlayerChange")},dsa=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},esa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Oe="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.N("previousNextChange")},Wra=function(a){g.jq(a.D);
a.D=g.hq((0,g.x)(a.Sh,a,1),864E5)},P8=function(a,b,c){c?K8("Sending: action="+b+", params="+g.Jg(c)):K8("Sending: action="+b);
a.g.sendMessage(b,c)},Q8=function(a){Q7.call(this,"ScreenServiceProxy");
this.Xc=a;this.i=[];this.i.push(this.Xc.$_s("screenChange",(0,g.x)(this.QN,this)));this.i.push(this.Xc.$_s("onlineScreenChange",(0,g.x)(this.vK,this)))},jsa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.$p("MDX_CONFIG")||b;Bqa();O6();R8||(R8=new I7(b?b.loungeApiHost:void 0),U6()&&(R8.g="/api/loungedev"));S8||(S8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",S8,void 0));fsa();var c=T8();if(!c){var d=new Z7(R8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=T8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Kra(a,d,function(m){m?U8()&&t8(U8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){y6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),V8("Initializing: "+g.Jg(b)),W8.push(g.oq("yt-remote-cast2-availability-change",function(){y6("yt-remote-receiver-availability-change")})),W8.push(g.oq("yt-remote-cast2-receiver-selected",function(){X8(null);
y6("yt-remote-auto-connect","cast-selector-receiver")})),W8.push(g.oq("yt-remote-cast2-receiver-resumed",function(){y6("yt-remote-receiver-resumed","cast-selector-receiver")})),W8.push(g.oq("yt-remote-cast2-session-change",gsa)),W8.push(g.oq("yt-remote-connection-change",function(m){m?t8(U8(),"YouTube TV"):Y8()||(t8(null,null),Nra())})),a=Z8(),b.isAuto&&(a.id+="#dial"),g.Wq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),V8(" -- with channel params: "+
g.Jg(a)),hsa(a),c.start(),U8()||isa())},lsa=function(){var a=ksa();
q8()&&g.Lt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},ksa=function(){var a=T8().Xc.$_gos();
var b=$8();b&&a9()&&(H6(a,b)||a.push(b));return Aqa(a)},b9=function(){var a=msa();
!a&&q8()&&Mra()&&(a={key:"cast-selector-receiver",name:Mra()});return a},msa=function(){var a=ksa(),b=$8();
b||(b=Y8());return g.Xa(a,function(c){return b&&B6(b,c.key)?!0:!1})},$8=function(){var a=U8();
if(!a)return null;var b=T8().Rd();return I6(b,a)},gsa=function(a){V8("remote.onCastSessionChange_: "+E6(a));
if(a){var b=$8();b&&b.id==a.id?t8(b.id,"YouTube TV"):(b&&c9(),d9(a,1))}else a9()&&c9()},c9=function(){r8()?o8().stopSession():m8("stopSession called before API ready.");
var a=a9();a&&(a.disconnect(1),e9(null))},f9=function(){var a=a9();
return!!a&&3!=a.getProxyState()},V8=function(a){M7("remote",a)},T8=function(){if(!g9){var a=g.w("yt.mdx.remote.screenService_");
g9=a?new Q8(a):null}return g9},U8=function(){return g.w("yt.mdx.remote.currentScreenId_")},nsa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},osa=function(){return g.w("yt.mdx.remote.connectData_")},X8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},a9=function(){return g.w("yt.mdx.remote.connection_")},e9=function(a){var b=a9();
X8(null);a||nsa("");g.Ga("yt.mdx.remote.connection_",a,void 0);S8&&((0,g.y)(S8,function(c){c(a)}),S8.length=0);
b&&!a?y6("yt-remote-connection-change",!1):!b&&a&&y6("yt-remote-connection-change",!0)},Y8=function(){var a=g.Mt();
if(!a)return null;var b=T8().Rd();return I6(b,a)},d9=function(a,b){$8()&&$8();
if(h9)i9=a;else{nsa(a.id);var c=new J8(R8,a,Z8());c.connect(b,osa());c.subscribe("beforeDisconnect",function(d){y6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){a9()&&e9(null)});
e9(c)}},isa=function(){var a=Y8();
a?(V8("Resume connection to: "+E6(a)),d9(a,0)):(S6(),Nra(),V8("Skipping connecting because no session screen found."))},fsa=function(){var a=Z8();
if(g.Xb(a)){a=N6();var b=g.Lt("yt-remote-session-name")||"",c=g.Lt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},Z8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},hsa=function(a){a?(g.Kt("yt-remote-session-app",a.app),g.Kt("yt-remote-session-name",a.name)):(J6("yt-remote-session-app"),J6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},j9=function(a,b,c){g.A.call(this);
this.u=a;this.i=b;this.l=new g.Xs(this);g.B(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.QJ);this.l.K(b,"captionschanged",this.OI);this.l.K(b,"captionssettingschanged",this.QA);this.l.K(b,"videoplayerreset",this.Wn);this.l.K(b,"mdxautoplaycancel",this.OC);this.P=this.l.K(b,"onVolumeChange",this.gz);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.sz,this);c.subscribe("remotePlayerChange",this.Ek,this);c.subscribe("remoteQueueChange",this.Wn,this);c.subscribe("autoplayUpNext",this.Vy,
this);c.subscribe("previousNextChange",this.pz,this);c.subscribe("nowAutoplaying",this.lz,this);c.subscribe("autoplayDismissed",this.Uy,this);this.suggestion=null;this.F=new g.TC(64);this.o=new g.J(this.OA,500,this);g.B(this,this.o);this.A=new g.J(this.PA,1E3,this);g.B(this,this.A);this.I=new a7(this.vN,0,this);g.B(this,this.I);this.B={};this.R=new g.J(this.rB,1E3,this);g.B(this,this.R);this.H=new g.Il(this.lG,1E3,this);g.B(this,this.H);this.M=g.Ha;this.QA();this.Wn();this.Ek()},k9=function(a,b){a.u.Oc(b,
a.i.getVideoData().lengthSeconds)},psa=function(a){k9(a,0);
a.o.stop();l9(a,new g.TC(64))},n9=function(a,b){if(m9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.FA(a.i.getVideoData(1).videoId,c);a.B=D8(a.g).g}},o9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Qe,t6(c));l9(a,new g.TC(1))},qsa=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{rR:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},m9=function(a){return D8(a.g).videoId==a.i.getVideoData(1).videoId},l9=function(a,b){a.A.stop();
var c=a.F;if(!g.ZC(c,b)){var d=g.T(b,2);d!=g.T(a.F,2)&&g.RK(a.i,d);a.F=b;rsa(a.u,c,b)}},p9=function(){g.V.call(this,{C:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{C:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{C:"div",G:"ytp-mdx-popup-title",V:"You're signed out"},{C:"div",G:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{C:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.l=new g.LQ(this,250);g.B(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},q9=function(a){g.V.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.$P()]},{C:"div",G:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.LQ(this,250);g.B(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);ssa(this,g.NK(a))},ssa=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.ZN("Error on $RECEIVER_NAME",c):g.$C(b)||g.T(b,4)?g.ZN("Playing on $RECEIVER_NAME",c):g.ZN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},r9=function(a,b){g.wU.call(this,"Play on",0,a,b);
this.l=a;this.B={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},s9=function(a){g.rL.call(this,a);
this.i={key:G6(),name:"This computer"};this.u=null;this.o=[];this.H=this.g=null;this.D=[this.i];this.l=this.i;this.mk=new g.TC(64);this.I=0;this.Xm=-1;this.A=null;if(!g.yz(g.X(this.player))){a=this.player;var b=g.ND(a);b&&(b=b.Dn())&&(b=new r9(a,b),g.B(this,b));b=new q9(a);g.B(this,b);g.bL(a,b.element,4);this.A=new p9;g.B(this,this.A);g.bL(a,this.A.element,4);this.F=!!Y8()}this.B=null},t9=function(a){a.B&&(a.player.removeEventListener("presentingplayerstatechange",a.B),a.B=null)},rsa=function(a,b,
c){a.mk=c;
a.player.N("presentingplayerstatechange",new g.dE(c,b))},u9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)c9();
else{var c;(c=!g.O(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.$p("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.$p("SESSION_INDEX")&&!g.$p("LOGGED_IN")))||a.F||!a.A);c||g.yz(g.X(a.player))||(g.$C(g.NK(a.player))?a.player.pauseVideo():(a.B=(0,g.x)(a.wM,a),a.player.addEventListener("presentingplayerstatechange",a.B)),a.A&&a.A.l.show(),a9()||(h9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();
if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.va(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Qe,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=t6(c))&&(d.locationInfo=c);c=d}else c=null;V8("Connecting to: "+g.Jg(b));"cast-selector-receiver"==b.key?(X8(c||null),r8()?o8().setLaunchParams(c||null):m8("setLaunchParams called before ready.")):!c&&f9()&&U8()==b.key?y6("yt-remote-connection-change",
!0):(c9(),X8(c||null),c=T8().Rd(),(c=I6(c,b.key))&&d9(c,1))}},qqa=/^https?$/i,tsa=["POST",
"PUT"];g.Sa(r6,g.Pf);g.h=r6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.Y=b;this.P=!1;this.i=!0;this.g=this.M?j6(this.M):j6(g.AZ);this.R=this.M?this.M.getOptions():g.AZ.getOptions();this.g.onreadystatechange=(0,g.x)(this.zw,this);try{g6(k6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){g6(k6(this,"Error opening Xhr: "+f.message));o6(this,f);return}a=
c||"";var e=this.headers.clone();d&&nqa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Pd(),oqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.$a(tsa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{l6(this),0<this.A&&(this.I=pqa(this.g),g6(k6(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.Aw,this)):this.F=g.Fg(this.Aw,this.A,this)),g6(k6(this,"Sending request")),this.B=!0,this.g.send(a),this.B=!1}catch(f){g6(k6(this,"Send error: "+f.message)),o6(this,f)}};
g.h.Aw=function(){"undefined"!=typeof g.cZ&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,k6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(k6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),n6(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),n6(this,!0));r6.fb.U.call(this)};
g.h.zw=function(){this.fa()||(this.aa||this.B||this.o?q6(this):this.SK())};
g.h.SK=function(){q6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<p6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.l)?this.l:String(this.l)};
var p7={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},o7={"'":"\\'"},usa={};g.h=x6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Yma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.Bc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var yqa={pO:"atp",EQ:"ska",tQ:"que",TP:"mus",DQ:"sus",lP:"dsp",AQ:"seq"};z6.prototype.hg=function(){var a=new z6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var T6,M6="",Gqa=V6("loadCastFramework")||V6("loadCastApplicationFramework"),Jra=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(a7,g.A);g.h=a7.prototype;g.h.ID=function(a){this.o=arguments;this.g=!1;this.Aa?this.l=(0,g.D)()+this.Yc:this.Aa=g.Fg(this.u,this.Yc)};
g.h.stop=function(){this.Aa&&(g.u.clearTimeout(this.Aa),this.Aa=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();a7.fb.U.call(this)};
g.h.JD=function(){this.l?(this.Aa=g.Fg(this.u,this.l-(0,g.D)()),this.l=null):(this.Aa=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};b7.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
b7.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};g.h=c7.prototype;g.h.bh=null;g.h.Ee=!1;g.h.aj=null;g.h.Ct=null;g.h.Ki=null;g.h.di=null;g.h.Zf=null;g.h.Eg=null;g.h.wh=null;g.h.tc=null;g.h.nl=0;g.h.Ie=null;g.h.No=null;g.h.qg=null;g.h.Tj=-1;g.h.sA=!0;g.h.Pg=!1;g.h.xq=0;g.h.ho=null;var j7={},h7={};g.h=c7.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.GM=function(a){a=a.target;var b=this.ho;b&&3==p6(a)?b.Pj():this.zB(a)};
g.h.zB=function(a){try{if(a==this.tc)a:{var b=p6(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Ld&&!g.md(10)||g.Nd&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Bh&&!s6(this.tc))break a;this.Pg||4!=b||7==c||(8==c||0>=d?this.g.Be(3):this.g.Be(2));s7(this);var e=this.tc.getStatus();this.Tj=e;var f=s6(this.tc);(this.Ee=200==e)?(4==b&&l7(this),this.u?(n7(this,b,f),g.Bh&&this.Ee&&3==b&&(this.ca.da(this.i,"tick",this.AM),this.i.start())):k7(this,f),this.Ee&&!this.Pg&&(4==b?this.g.Tn(this):(this.Ee=
!1,g7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.qg=3,i7(13)):(this.qg=0,i7(14)),l7(this),m7(this))}}catch(k){this.tc&&s6(this.tc)}finally{}};
g.h.AM=function(){var a=p6(this.tc),b=s6(this.tc);this.nl<b.length&&(s7(this),n7(this,a,b),this.Ee&&4!=a&&g7(this))};
g.h.TL=function(a){r7((0,g.x)(this.SL,this,a),0)};
g.h.SL=function(a){this.Pg||(s7(this),k7(this,a),g7(this))};
g.h.Az=function(a){r7((0,g.x)(this.RL,this,a),0)};
g.h.RL=function(a){this.Pg||(l7(this),this.Ee=a,this.g.Tn(this),this.g.Be(4))};
g.h.cancel=function(){this.Pg=!0;l7(this)};
g.h.dM=function(){this.aj=null;var a=(0,g.D)();0<=a-this.Ct?(2!=this.di&&this.g.Be(3),l7(this),this.qg=2,i7(18),m7(this)):Jqa(this,this.Ct-a)};
g.h.getLastError=function(){return this.qg};g.h=Mqa.prototype;g.h.uq=null;g.h.Hd=null;g.h.jo=!1;g.h.yw=null;g.h.om=null;g.h.dr=null;g.h.wq=null;g.h.he=null;g.h.Bf=-1;g.h.Sj=null;g.h.mj=null;g.h.connect=function(a){this.wq=a;a=u7(this.g,null,this.wq);i7(3);this.yw=(0,g.D)();var b=this.g.D;null!=b?(this.Sj=b[0],(this.mj=b[1])?(this.he=1,Nqa(this)):(this.he=2,w7(this))):(i6(a,"MODE","init"),this.Hd=new c7(this,void 0,void 0,void 0),this.Hd.bh=this.uq,f7(this.Hd,a,!1,null,!0),this.he=0)};
g.h.PC=function(a){if(a)this.he=2,w7(this);else{i7(4);var b=this.g;b.Ne=b.gg.Bf;D7(b,9)}a&&this.Be(2)};
g.h.Pp=function(a){return this.g.Pp(a)};
g.h.abort=function(){this.Hd&&(this.Hd.cancel(),this.Hd=null);this.Bf=-1};
g.h.xw=function(){return!1};
g.h.uz=function(a,b){this.Bf=a.Tj;if(0==this.he)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ne=this.Bf;D7(c,2);return}this.Sj=c[0];this.mj=c[1]}else c=this.g,c.Ne=this.Bf,D7(c,2);else if(2==this.he)if(this.jo)i7(7),this.dr=(0,g.D)();else if("11111"==b){if(i7(6),this.jo=!0,this.om=(0,g.D)(),c=this.om-this.yw,!g.Ld||g.md(10)||500>c)this.Bf=200,this.Hd.cancel(),i7(12),v7(this.g,this,!0)}else i7(8),this.om=this.dr=(0,g.D)(),this.jo=!1};
g.h.Tn=function(){this.Bf=this.Hd.Tj;if(this.Hd.Ee)0==this.he?this.mj?(this.he=1,Nqa(this)):(this.he=2,w7(this)):2==this.he&&((!g.Ld||g.md(10)?!this.jo:200>this.dr-this.om)?(i7(11),v7(this.g,this,!1)):(i7(12),v7(this.g,this,!0)));else{0==this.he?i7(9):2==this.he&&i7(10);var a=this.g;this.Hd.getLastError();a.Ne=this.Bf;D7(a,2)}};
g.h.Vk=function(){return this.g.Vk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Be=function(a){this.g.Be(a)};g.h=x7.prototype;g.h.Aj=null;g.h.Ed=null;g.h.Tb=null;g.h.tq=null;g.h.qm=null;g.h.Ku=null;g.h.Fm=null;g.h.zk=0;g.h.hI=0;g.h.Vc=null;g.h.ng=null;g.h.rf=null;g.h.Ug=null;g.h.gg=null;g.h.Lo=null;g.h.oi=-1;g.h.kx=-1;g.h.Ne=-1;g.h.Wh=0;g.h.Oh=0;g.h.Qg=8;var E7=new g.Pf;g.Sa(Pqa,g.rf);g.Sa(Qqa,g.rf);g.Sa(Rqa,g.rf);g.h=x7.prototype;g.h.connect=function(a,b,c,d,e){i7(0);this.tq=b;this.Aj=c||{};d&&g.Ca(e)&&(this.Aj.OSID=d,this.Aj.OAID=e);this.A?(r7((0,g.x)(this.ev,this,a),100),Vqa(this)):this.ev(a)};
g.h.ev=function(a){this.gg=new Mqa(this);this.gg.uq=null;this.gg.i=this.u;this.gg.connect(a)};
g.h.xw=function(){return 0==this.g};
g.h.zz=function(a){this.ng=null;Yqa(this,a)};
g.h.yz=function(){this.rf=null;this.Tb=new c7(this,this.l,"rpc",this.B);this.Tb.bh=null;this.Tb.xq=0;var a=this.Ku.clone();g.tn(a,"RID","rpc");g.tn(a,"SID",this.l);g.tn(a,"CI",this.Lo?"0":"1");g.tn(a,"AID",this.oi);y7(this,a);if(!g.Ld||g.md(10))g.tn(a,"TYPE","xmlhttp"),f7(this.Tb,a,!0,this.Fm,!1);else{g.tn(a,"TYPE","html");var b=this.Tb,c=!!this.Fm;b.di=3;b.Zf=h6(a.clone());q7(b,c)}};
g.h.uz=function(a,b){if(0!=this.g&&(this.Tb==a||this.Ed==a))if(this.Ne=a.Tj,this.Ed==a&&3==this.g)if(7<this.Qg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.rf){if(this.Tb)if(this.Tb.Ki+3E3<this.Ed.Ki)A7(this),this.Tb.cancel(),this.Tb=null;else break a;C7(this);i7(19)}}else this.kx=c[1],0<this.kx-this.oi&&37500>c[2]&&this.Lo&&0==this.Oh&&!this.Ug&&(this.Ug=r7((0,g.x)(this.KI,this),6E3));else D7(this,11)}else b!=usa.MO.g&&D7(this,11);else if(this.Tb==a&&
A7(this),!g.wb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.oi=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Fm=e[2],e=e[3],null!=e?this.Qg=e:this.Qg=6,this.g=3,this.Vc&&this.Vc.Yu(),this.Ku=u7(this,this.Vk()?this.Fm:null,this.tq),Zqa(this)):"stop"==e[0]&&D7(this,7):3==this.g&&("stop"==e[0]?D7(this,7):"noop"!=e[0]&&this.Vc&&this.Vc.Xu(e),this.Oh=0)}}};
g.h.KI=function(){null!=this.Ug&&(this.Ug=null,this.Tb.cancel(),this.Tb=null,C7(this),i7(20))};
g.h.Tn=function(a){if(this.Tb==a){A7(this);this.Tb=null;var b=2}else if(this.Ed==a)this.Ed=null,b=1;else return;this.Ne=a.Tj;if(0!=this.g)if(a.Ee)1==b?(b=(0,g.D)()-a.Ki,E7.dispatchEvent(new Qqa(E7,a.wh?a.wh.length:0,b,this.Wh)),z7(this),this.o.length=0):Zqa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ne)){if(d=1==b)this.Ed||this.ng||1==this.g||2<=this.Wh?d=!1:(this.ng=r7((0,g.x)(this.zz,this,a),$qa(this,this.Wh)),this.Wh++,d=!0);d=!(d||2==b&&C7(this))}if(d)switch(c){case 1:D7(this,
5);break;case 4:D7(this,10);break;case 3:D7(this,6);break;case 7:D7(this,12);break;default:D7(this,2)}}};
g.h.hD=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.mN=function(a){a?i7(2):(i7(1),ara(this,8))};
g.h.Pp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new r6;a.T=!1;return a};
g.h.isActive=function(){return!!this.Vc&&this.Vc.isActive(this)};
g.h.Be=function(a){E7.dispatchEvent(new Rqa(E7,a))};
g.h.Vk=function(){return!(!g.Ld||g.md(10))};
g.h=bra.prototype;g.h.Yu=function(){};
g.h.Xu=function(){};
g.h.Wu=function(){};
g.h.Bp=function(){};
g.h.Vv=function(){return{}};
g.h.isActive=function(){return!0};g.Sa(F7,g.A);g.h=F7.prototype;g.h.LL=function(){this.Yc=Math.min(3E5,2*this.Yc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Yc+15E3*Math.random();g.Eo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Yc=5E3};g.Sa(G7,bra);g.h=G7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.eh(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.jb||(this.jb=!0,g.pf(this.l),era(this),g.pf(this.i),this.i=null)};
g.h.fa=function(){return this.jb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new x7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Vc=null);d.Vc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.oi):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):H7(this)&&Wqa(this.g,c)};
g.h.Yu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)Wqa(this.g,a[b])}this.N("handlerOpened")};
g.h.Wu=function(a){var b=2==a&&401==this.g.Ne;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Bp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.Vv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.Xu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),Uqa(this.g)):this.N("handlerMessage",new cra(a[0],a[1]))};
g.h.RM=function(){this.i.isActive();var a=this.g,b=0;a.Tb&&b++;a.Ed&&b++;0==b&&this.connect(this.u,this.o)};I7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
I7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
I7.prototype.u=function(a){a(Error("request timed out"))};var mra=(0,g.D)(),L7=null,O7=Array(50),N7=-1,P7=!1;g.Sa(Q7,g.N);Q7.prototype.Rd=function(){return this.g};
Q7.prototype.contains=function(a){return!!H6(this.g,a)};
Q7.prototype.get=function(a){return a?I6(this.g,a):null};
Q7.prototype.info=function(a){M7(this.B,a)};g.t(R7,g.N);g.h=R7.prototype;g.h.start=function(){!this.g&&isNaN(this.Aa)&&this.CB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Aa)||(g.jq(this.Aa),this.Aa=NaN)};
g.h.U=function(){this.stop();g.N.prototype.U.call(this)};
g.h.CB=function(){this.Aa=NaN;this.g=g.er(J7(this.A,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.ON,this),onError:(0,g.x)(this.NN,this),oe:(0,g.x)(this.PN,this)})};
g.h.ON=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new A6(c))};
g.h.NN=function(a){this.g=null;a.status&&404==a.status?this.i>=vsa.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=vsa[this.i],this.Aa=g.hq((0,g.x)(this.CB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.PN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var vsa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(T7,Q7);g.h=T7.prototype;g.h.start=function(){S7(this)&&this.N("screenChange");!g.Lt("yt-remote-lounge-token-expiration")&&qra(this);g.jq(this.i);this.i=g.hq((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){S7(this);nra(this,a);U7(this,!1);this.N("screenChange");b(a);a.token||qra(this)};
g.h.remove=function(a,b){var c=S7(this);pra(this,a)&&(U7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Ho=function(a,b,c,d){var e=S7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,U7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.jq(this.i);T7.fb.U.call(this)};
g.h.TD=function(a){S7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}U7(this,!b);b&&M7(this.B,"Missed "+b+" lounge tokens.")};
g.h.SD=function(a){M7(this.B,"Requesting lounge tokens failed: "+a)};g.t(W7,g.N);g.h=W7.prototype;g.h.start=function(){var a=parseInt(g.Lt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?Y7(this):(this.o=(0,g.D)()+3E5,g.Kt("yt-remote-fast-check-period",this.o),this.Gs())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){V7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!I6(a,d)},this);
X7(this,b)};
g.h.U=function(){g.jq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.N.prototype.U.call(this)};
g.h.Gs=function(){g.jq(this.l);this.l=NaN;this.i&&this.i.abort();var a=tra(this);if(u6(a)){var b=J7(this.u,"/pairing/get_screen_availability");this.i=K7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.oL,this,a),(0,g.x)(this.nL,this))}else X7(this,{}),Y7(this)};
g.h.oL=function(a,b){this.i=null;var c=g.Rb(tra(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;X7(this,d);Y7(this)}else this.Ib("Changing Screen set during request."),this.Gs()};
g.h.nL=function(a){this.Ib("Screen availability failed: "+a);this.i=null;Y7(this)};
g.h.Ib=function(a){M7("OnlineScreenService",a)};g.Sa(Z7,Q7);g.h=Z7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Ho=function(a,b,c,d){this.l.contains(a)?this.l.Ho(a,b,c,d):(a="Updating name of unknown screen: "+a.name,M7(this.B,a),d(Error(a)))};
g.h.Rd=function(a){return a?this.g:g.fb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.DB=function(){return(0,g.Xd)(this.Rd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.EB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new R7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.pf(f);d($7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.pf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.RN=function(a,b,c,d){g.er(J7(this.A,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new A6(f.screen||{});if(!k.name||xra(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);xra(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c($7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
oe:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.pf(this.l);g.pf(this.i);Z7.fb.U.call(this)};
g.h.bE=function(){yra(this);this.N("screenChange");this.i.update()};
Z7.prototype.dispose=Z7.prototype.dispose;g.Sa(b8,g.N);g.h=b8.prototype;g.h.Vn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Ud=function(a){this.fa()||(a&&c8(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){M7(this.R,a)};
g.h.GB=function(){return null};
g.h.Ps=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){c8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Ps("");b8.fb.U.call(this)};g.Sa(d8,b8);g.h=d8.prototype;g.h.Os=function(a){if(this.g){if(this.g==a)return;c8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Ara(this)};
g.h.ri=function(a){this.info("launchWithParams no-op for Cast: "+g.Jg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Ud()},this),(0,g.x)(function(){this.Ud(Error("Failed to stop receiver app."))},this)):this.Ud(Error("Stopping cast device witout session."))};
g.h.Ps=g.Ha;g.h.U=function(){this.info("disposeInternal");g.jq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;d8.fb.U.call(this)};
g.h.oM=function(a,b){if(!this.fa())if(b){var c=w6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Jg(c));switch(d){case "mdxSessionStatus":zra(this,c.screenId);break;default:c8(this,"Unknown youtube message: "+d)}}else c8(this,"Unable to parse message.")}else c8(this,"No data in message.")};
g.h.nw=function(a,b,c,d){wra(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(c8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.hq((0,g.x)(this.nw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.GB=function(){return this.g};
g.h.SN=function(a){this.fa()||a||(c8(this,"Cast session died."),this.Ud())};g.Sa(e8,b8);g.h=e8.prototype;g.h.Os=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ri=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ha;g.jq(this.A);this.o?this.o.stop((0,g.x)(this.Ud,this,null),(0,g.x)(this.Ud,this,"Failed to stop DIAL device.")):this.Ud()};
g.h.U=function(){this.g();this.g=g.Ha;g.jq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;e8.fb.U.call(this)};
g.h.VN=function(a){this.fa()||a||(c8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Ud())};
g.h.Jq=function(a){this.H=G6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Cra(this));a(b);Bra(this)}else this.B=(0,g.x)(function(){g.jq(this.A);this.B=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Cra(this));a(c);Bra(this)},this),this.A=g.hq((0,g.x)(function(){this.B()},this),100)};
g.h.xE=function(a,b,c){wra(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Vn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Jq(b,c)},this),(0,g.x)(function(d){c8(this,"Failed to get DIAL screen: "+d);
this.Jq(b,c)},this))};g.Sa(f8,b8);f8.prototype.stop=function(){this.Ud()};
f8.prototype.Os=g.Ha;f8.prototype.ri=function(){g.jq(this.g);this.g=NaN;var a=I6(this.F.Rd(),this.i.label);a?this.Vn(a):this.Ud(Error("No such screen"))};
f8.prototype.U=function(){g.jq(this.g);this.g=NaN;f8.fb.U.call(this)};g.Sa(g8,g.N);g.h=g8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.XK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.wz,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.lJ,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),jra(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.FB,this)),this.l=Era(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Ib("Failed to set initial custom receivers: "+g.Jg(k))},this)),this.N("yt-remote-cast2-availability-change",i8(this)),b(!0))},this),(0,g.x)(function(k){this.Ib("Failed to initialize API: "+g.Jg(k));
b(!1)},this))};
g.h.aN=function(a,b){h8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)h8("Unsetting old screen status: "+this.g.i.friendlyName),j8(this,null)}if(a&&b){if(!this.g){c=I6(this.i.Rd(),a);if(!c){h8("setConnectedScreenStatus: Unknown screen.");return}var d=Dra(this,c);d||(h8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Ib("Failed to set initial custom receivers: "+g.Jg(e))},this)));
h8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);j8(this,new f8(this.i,d),!0)}this.g.Ps(b)}else h8("setConnectedScreenStatus: no screen.")};
g.h.bN=function(a){this.fa()?this.Ib("Setting connection data on disposed cast v2"):this.g?this.g.ri(a):this.Ib("Setting connection data without a session")};
g.h.UN=function(){this.fa()?this.Ib("Stopping session on disposed cast v2"):this.g?(this.g.stop(),j8(this,null)):h8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.wz,this),(0,g.x)(this.uL,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.FB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.w("yt.mdx.remote.debug.handlers_")||[],gra);g.pf(this.g);g8.fb.U.call(this)};
g.h.Ib=function(a){M7("Controller",a)};
g.h.xz=function(a,b){this.g==a&&(b||j8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.TK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),h8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)h8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{h8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:j8(this,
new f8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:j8(this,new e8(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:j8(this,new d8(this.i,a));break;default:this.Ib("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Ib("Stopping receiver w/o session: "+a.friendlyName)}else this.Ib("onReceiverAction_ called without receiver.")};
g.h.lJ=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ib("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Ib("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return h8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ib('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);j8(this,new e8(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.xE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Jq,b))};
g.h.wz=function(a){if(!this.fa()){h8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)h8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),j8(this,new d8(this.i,b),!0);else{this.Ib("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=I6(this.i.Rd(),c.label);d&&B6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(h8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.pf(this.g),this.g=new d8(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.xz,this,this.g)),this.g.ri(null));this.g.Os(a)}}};
g.h.TN=function(){return this.g?this.g.GB():null};
g.h.uL=function(a){this.fa()||(this.Ib("Failed to estabilish a session: "+g.Jg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&j8(this,null))};
g.h.XK=function(a){h8("Receiver availability updated: "+a);if(!this.fa()){var b=i8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;i8(this)!=b&&this.N("yt-remote-cast2-availability-change",i8(this))}};
g.h.FB=function(){this.fa()||(this.l=Era(this),h8("Updating custom receivers: "+g.Jg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Ib("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",i8(this)))};
g8.prototype.setLaunchParams=g8.prototype.bN;g8.prototype.setConnectedScreenStatus=g8.prototype.aN;g8.prototype.stopSession=g8.prototype.UN;g8.prototype.getCastSession=g8.prototype.TN;g8.prototype.requestSession=g8.prototype.requestSession;g8.prototype.init=g8.prototype.init;g8.prototype.dispose=g8.prototype.dispose;var p8=[];u8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";v8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Oe=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
u8.prototype.isAdPlaying=function(){return 1081==this.playerState};
u8.prototype.getDuration=function(){return this.u?this.D+w8(this):this.D};
u8.prototype.clone=function(){return new u8(A8(this))};g.t(C8,g.N);g.h=C8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,I8(this,"play")):H8(this,"play"),G8(this,1,y8(D8(this))),this.N("remotePlayerChange")):E8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,I8(this,"pause")):H8(this,"pause"),G8(this,2,y8(D8(this))),this.N("remotePlayerChange")):E8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=D8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,I8(this,"seekTo",{newTime:a}))}else H8(this,"seekTo",{newTime:a});G8(this,3,a);this.N("remotePlayerChange")}else E8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,I8(this,"stopVideo")):H8(this,"stopVideo");var a=D8(this);a.index=-1;a.videoId="";v8(a);F8(this,a);this.N("remotePlayerChange")}else E8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=D8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){M7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Ib("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){M7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Ib("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);H8(this,"setVolume",e)}c.muted=b;c.volume=a;F8(this,c)}else E8(this,g.Qa(this.setVolume,a,b))};
g.h.FA=function(a,b){if(1==this.g){var c=D8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Jg(b.style),g.ec(d,c.g));H8(this,"setSubtitlesTrack",d);F8(this,c)}else E8(this,g.Qa(this.FA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();H8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=D8(this);d.audioTrackId=c;F8(this,d)}else E8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=D8(this);c=c||0;var m={videoId:a,currentIndex:c};z8(l,a,c);g.Ca(b)&&(x8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Jg(k));H8(this,"setPlaylist",m);d||F8(this,l)};
g.h.ao=function(a,b){if(1==this.g){if(a&&b){var c=D8(this);z8(c,a,b);F8(this,c)}H8(this,"previous")}else E8(this,g.Qa(this.ao,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=D8(this);z8(c,a,b);F8(this,c)}H8(this,"next")}else E8(this,g.Qa(this.nextVideo,a,b))};
g.h.Cv=function(){1==this.g?H8(this,"dismissAutoplay"):E8(this,this.Cv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.N.prototype.dispose.call(this)};
g.h.U=function(){Rra(this);this.o=null;this.u.clear();B8(this,null);g.N.prototype.U.call(this)};
g.h.Ft=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.QK=function(a,b){this.N(a,b)};
g.h.RI=function(a){if(!a)this.Ck(null),B8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=D8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)M7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,F8(this,b)}};
g.h.Ck=function(a){M7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Sra(this),this.N("remotePlayerChange")};
g.h.QI=function(a){a?(Sra(this),this.N("remotePlayerChange")):this.Ck(null)};
g.h.kt=function(){H8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.eJ=function(){var a=Ora();a&&B8(this,a)};
g.h.Ib=function(a){M7("CP",a)};g.t(J8,g.N);g.h=J8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;x8(this.Pa,m);this.o="UNSUPPORTED";K8("Connecting with setPlaylist and params: "+g.Jg(l));this.g.connect({method:"setPlaylist",
params:g.Jg(l)},a,P6())}else K8("Connecting without params"),this.g.connect({},a,P6());Ura(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),L8(this,3));g.N.prototype.dispose.call(this)};
g.h.U=function(){M8(this);O8(this);N8(this);g.jq(this.B);this.B=NaN;g.jq(this.D);this.D=NaN;this.l=null;g.os(this.R);this.R.length=0;this.g.dispose();g.N.prototype.U.call(this);this.o=this.A=this.i=this.Pa=this.g=null};
g.h.MD=function(){this.Sh(2)};
g.h.VI=function(){K8("Channel opened");this.I&&(this.I=!1,N8(this),this.H=g.hq((0,g.x)(function(){K8("Timing out waiting for a screen.");this.Sh(1)},this),15E3));
Eqa(dra(this.g),this.M)};
g.h.SI=function(){K8("Channel closed");isNaN(this.u)?S6(!0):S6();this.dispose()};
g.h.TI=function(a){S6();isNaN(this.Ij())?(K8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,K8("Channel error: "+a+" with reconnection in "+this.Ij()+" ms"),L8(this,2))};
g.h.UI=function(a){a.params?K8("Received: action="+a.action+", params="+g.Jg(a.params)):K8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=w6(a.params.devices);this.i=(0,g.ge)(a,function(c){return new z6(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Xra(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Xra(this,!1);break;case "remoteConnected":var b=new z6(w6(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||tqa(this.i,b);
break;case "remoteDisconnected":b=new z6(w6(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Zra(this,a);break;case "nowPlaying":asa(this,a);break;case "onStateChange":$ra(this,a);break;case "onAdStateChange":bsa(this,a);break;case "onVolumeChanged":csa(this,a);break;case "onSubtitlesTrackChanged":Yra(this,a);break;case "nowAutoplaying":dsa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":esa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:K8("Unrecognized action: "+a.action)}};
g.h.OM=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&P8(this,"getNowPlaying")}};
g.h.CD=function(){var a=3;this.fa()||(a=0,isNaN(this.Ij())?H7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Sh=function(a){K8("Disconnecting with "+a);M8(this);this.N("beforeDisconnect",a);1==a&&S6();era(this.g,a);this.dispose()};
g.h.BD=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),z8(a,this.l,a.index));return A8(a)};
g.h.cN=function(a){var b=new u8(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.jq(this.B),this.B=g.hq((0,g.x)(this.OM,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&y8(this.Pa)==y8(b)&&g.Jg(this.Pa.g)==g.Jg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.y)(c,function(d){this.N(d)},this)};
g.h.lw=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Ij=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.uD=function(){return this.o||"UNSUPPORTED"};
g.h.vD=function(){return this.A||""};
g.h.MN=function(){if(!isNaN(this.Ij())){var a=this.g.i;g.Fo(a.g);a.start()}};
g.h.VM=function(a,b){P8(this,a,b);Wra(this)};
J8.prototype.subscribe=J8.prototype.subscribe;J8.prototype.unsubscribeByKey=J8.prototype.Kf;J8.prototype.getProxyState=J8.prototype.CD;J8.prototype.disconnect=J8.prototype.Sh;J8.prototype.getPlayerContextData=J8.prototype.BD;J8.prototype.setPlayerContextData=J8.prototype.cN;J8.prototype.getOtherConnectedRemoteId=J8.prototype.lw;J8.prototype.getReconnectTimeout=J8.prototype.Ij;J8.prototype.getAutoplayMode=J8.prototype.uD;J8.prototype.getAutoplayVideoId=J8.prototype.vD;J8.prototype.reconnect=J8.prototype.MN;
J8.prototype.sendMessage=J8.prototype.VM;g.t(Q8,Q7);g.h=Q8.prototype;g.h.Rd=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.add=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.Ho=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Xc.$_ubk(this.i[a]);this.i.length=0;this.Xc=null;Q7.prototype.U.call(this)};
g.h.QN=function(){this.N("screenChange")};
g.h.vK=function(){this.N("onlineScreenChange")};
Z7.prototype.$_st=Z7.prototype.start;Z7.prototype.$_gspc=Z7.prototype.RN;Z7.prototype.$_gsppc=Z7.prototype.EB;Z7.prototype.$_c=Z7.prototype.contains;Z7.prototype.$_g=Z7.prototype.get;Z7.prototype.$_a=Z7.prototype.add;Z7.prototype.$_un=Z7.prototype.Ho;Z7.prototype.$_r=Z7.prototype.remove;Z7.prototype.$_gs=Z7.prototype.Rd;Z7.prototype.$_gos=Z7.prototype.DB;Z7.prototype.$_s=Z7.prototype.subscribe;Z7.prototype.$_ubk=Z7.prototype.Kf;var i9=null,h9=!1,R8=null,S8=null,g9=null,W8=[];g.t(j9,g.A);g.h=j9.prototype;
g.h.U=function(){g.A.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.sz,this);this.g.unsubscribe("remotePlayerChange",this.Ek,this);this.g.unsubscribe("remoteQueueChange",this.Wn,this);this.g.unsubscribe("autoplayUpNext",this.Vy,this);this.g.unsubscribe("previousNextChange",this.pz,this);this.g.unsubscribe("nowAutoplaying",this.lz,this);this.g.unsubscribe("autoplayDismissed",this.Uy,this);this.g=this.u=null};
g.h.Qx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(m9(this)){if(!D8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==D8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Pj(c[0],c[1]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":c=c[0],m9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();o9(this,0==c?void 0:c);break;case "control_seek":o9(this,c[0]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":c=c[0],m9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.OI=function(a){this.I.ID(a)};
g.h.vN=function(a){this.Qx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.QA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||n9(this,a)};
g.h.gz=function(a){if(m9(this)){this.g.unsubscribe("remotePlayerChange",this.Ek,this);var b=Math.round(a.volume);a=!!a.muted;var c=D8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.Ek,this)}};
g.h.QJ=function(){g.Xb(this.B)||qsa(this,this.B);this.D=!1};
g.h.sz=function(a,b){this.A.stop();2==b&&this.PA()};
g.h.Ek=function(){if(m9(this)){this.o.stop();var a=D8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Xm=1;break;case 1082:case 1083:this.u.Xm=0;break;default:this.u.Xm=-1}switch(a.playerState){case 1081:case 1:l9(this,new g.TC(8));this.OA();break;case 1085:case 3:l9(this,new g.TC(9));break;case 1083:case 0:l9(this,new g.TC(2));this.H.stop();k9(this,this.i.getVideoData().lengthSeconds);break;case 1084:l9(this,new g.TC(4));break;case 2:l9(this,new g.TC(4));k9(this,y8(a));
break;case -1:l9(this,new g.TC(64));break;case -1E3:l9(this,new g.TC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=D8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,qsa(this,a));a=D8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.rB()}else psa(this)};
g.h.pz=function(){this.i.N("mdxpreviousnextchange")};
g.h.Wn=function(){m9(this)||psa(this)};
g.h.OC=function(){this.g.Cv()};
g.h.Vy=function(a){a&&(a=g.er("/watch_queue_ajax",{method:"GET",ud:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.WL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.WL=function(a,b){var c=new g.CB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.lz=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Uy=function(){this.i.N("mdxautoplaycanceled")};
g.h.lG=function(a,b){-1==D8(this.g).playerState?o9(this,a):b&&this.g.seekTo(a)};
g.h.rB=function(){if(m9(this)){var a=D8(this.g);this.l.Na(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.K(this.i,"onVolumeChange",this.gz)}};
g.h.OA=function(){this.o.stop();if(!this.g.fa()){var a=D8(this.g);1==a.playerState&&l9(this,new g.TC(8));k9(this,y8(a));this.o.start()}};
g.h.PA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(p9,g.V);p9.prototype.o=function(){y6("mdx-privacy-popup-cancel");this.l.hide()};
p9.prototype.A=function(){y6("mdx-privacy-popup-confirm");this.l.hide()};g.t(q9,g.V);q9.prototype.u=function(a){ssa(this,a.state)};g.t(r9,g.wU);r9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.tb(a,this.A,this),g.yU(this,(0,g.ge)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.me(this.A(a)),this.enable(!0)):this.enable(!1)};
r9.prototype.A=function(a){return a.key};
r9.prototype.Ae=function(a){return"cast-selector-receiver"==a?"Cast...":this.B[a].name};
r9.prototype.Mc=function(a){g.wU.prototype.Mc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.ob()};g.t(s9,g.rL);g.h=s9.prototype;
g.h.create=function(){jsa(g.iz(g.X(this.player)));this.o.push(g.oq("yt-remote-before-disconnect",this.LI,this));this.o.push(g.oq("yt-remote-connection-change",this.YK,this));this.o.push(g.oq("yt-remote-receiver-availability-change",this.qz,this));this.o.push(g.oq("yt-remote-auto-connect",this.WK,this));this.o.push(g.oq("yt-remote-receiver-resumed",this.VK,this));this.o.push(g.oq("mdx-privacy-popup-confirm",this.DM,this));this.o.push(g.oq("mdx-privacy-popup-cancel",this.CM,this));this.qz()};
g.h.load=function(){this.player.cancelPlayback();g.rL.prototype.load.call(this);this.u=new j9(this,this.player,this.g);var a=(a=osa())?a.currentTime:0;var b=f9()?new C8(a9(),void 0):null;0==a&&b&&(a=y8(D8(b)));0!=a&&this.Oc(a);rsa(this,this.mk,this.mk);g.yY(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.qf(this.u,this.g);this.g=this.u=null;g.rL.prototype.unload.call(this);g.yY(this.player.app,5);t9(this)};
g.h.U=function(){g.pq(this.o);g.rL.prototype.U.call(this)};
g.h.cf=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Qx.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Xm};
g.h.ED=function(){return this.loaded?this.u.suggestion:null};
g.h.Oe=function(){return this.g?D8(this.g).Oe:!1};
g.h.hasNext=function(){return this.g?D8(this.g).hasNext:!1};
g.h.Oc=function(a,b){this.I=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=D8(this.g),b=this.player.getVideoData();return{allowSeeking:g.O(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+w8(a):a.l,isAtLiveHead:1>=(a.u?a.i+w8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+w8(a):a.i,seekableStart:0<a.o?a.o+
w8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.ao=function(){this.g&&this.g.ao()};
g.h.LI=function(a){1==a&&(this.H=this.g?D8(this.g):null)};
g.h.YK=function(){var a=f9()?new C8(a9(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.H=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.pf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.H)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,y8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.qz=function(){this.D=[this.i].concat(lsa());var a=b9()||this.i;u9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.wM=function(a){!this.F&&g.fE(a,8)&&(this.player.pauseVideo(),t9(this))};
g.h.WK=function(){var a=b9();u9(this,a)};
g.h.VK=function(){this.l=b9()};
g.h.DM=function(){this.F=!0;t9(this);h9=!1;i9&&d9(i9,1);i9=null};
g.h.CM=function(){this.F=!1;t9(this);u9(this,this.i);this.l=this.i;h9=!1;i9=null;this.player.playVideo()};
g.h.xc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.D;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?s8():u9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.D.length&&"cast-selector-receiver"==this.D[1].key?(b&&s8(),!0):!1}};
g.h.kt=function(){this.g.kt()};
g.h.Db=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.NV.remote=s9;})(_yt_player);
